import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :dash, DashWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section and set your `:url` port to 443:
#
#     config :dash, DashWeb.Endpoint,
#       ...,
#       url: [host: "example.com", port: 443],
#       https: [
#         ...,
#         port: 443,
#         cipher_suite: :strong,
#         keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
#         certfile: System.get_env("SOME_APP_SSL_CERT_PATH")
#       ]
#
# The `cipher_suite` is set to `:strong` to support only the
# latest and more secure SSL ciphers. This means old browsers
# and clients may not be supported. You can set it to
# `:compatible` for wider support.
#
# `:keyfile` and `:certfile` expect an absolute path to the key
# and cert in disk or a relative path inside priv, for example
# "priv/ssl/server.key". For all supported SSL configuration
# options, see https://hexdocs.pm/plug/Plug.SSL.html#configure/1
#
# We also recommend setting `force_ssl` in your endpoint, ensuring
# no data is ever sent via http, always redirecting to https:
#
#     config :dash, DashWeb.Endpoint,
#       force_ssl: [hsts: true]
#
# Check `Plug.SSL` for all available options in `force_ssl`.

config :dash, Dash.OrchClient, orch_host: "turkeyorch:889"

config :dash, Dash.RetClient,
  timeout_ms: 600_000,
  wait_ms: 2000

config :dash, Dash.FeatureFlags,
  create_hubs: false,
  delete_hubs: false,
  tier_selection: false,
  ccu_selection: false,
  storage_selection: false

config :dash, DashWeb.Plugs.BasicAuth, enabled: false

config :dash, Dash.HubStat, enable_hub_stats: true

config :dash, Dash.ApprovedEmail, enabled: false

config :dash, Dash.Scheduler,
  jobs: [
    # Runs every midnight:
    {"@daily", {Dash.HubStat, :job_record_hub_stats, []}}
  ]

config :sentry,
  # Data Source Names (DSN) are safe to keep public because they only allow
  # submission of new events and related event data; they do not allow read
  # access to any information.
  dsn: "https://0688486cc05c4c2e977393eb607bb390@o1069899.ingest.sentry.io/4505037614678016",
  enable_source_code_context: true,
  environment_name: System.get_env("ENVIRONMENT_NAME", "unnamed"),
  included_environments: ["production", "staging"],
  root_source_code_path: File.cwd!()
