name: lint-and-test

on: [push, workflow_dispatch]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  lint-and-test-frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - run: npm ci
        working-directory: assets
      - run: npm run lint
        working-directory: assets
      - run: npm run test
        working-directory: assets

      - run: npm config set -- "//npm.pkg.github.com/:_authToken" "$GITHUB_TOKEN" && npm ci --legacy-peer-deps
        working-directory: client
      - run: npm run lint
        working-directory: client

      - run: npm config set -- "//npm.pkg.github.com/:_authToken" "$GITHUB_TOKEN" && npm ci --legacy-peer-deps
        working-directory: marketing
      - run: npm run lint
        working-directory: marketing

  lint-and-test-backend:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-beam@v1
        with:
          otp-version: 24
          elixir-version: 1.13
          
      - uses: actions/cache@v3.0.2
        with:
          path: |
            deps
            _build
          key: mix-${{ hashFiles('mix.lock') }}

      - run: mix deps.get
      - run: mix format --check-formatted '{lib,priv,test,config}/**/*.{ex,exs}'
      - run: mix compile --force --warnings-as-errors
      - run: mix test
