name: lint-and-test
on:
  push:
    branches:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: lint-and-test
        run: |
          cd assets
          npm ci
          npm run lint
          npm run test
