name: Storybook
on:
  push:
    branches:
      - may-comp-lib
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        
      - name: Deploy Storybook
        run: |
          cd client
          npm ci
          npm run deploy-storybook -- --ci