name: Storybook
on:
  push:
    branches:
      - HUBSTRKY-421
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        
      - name: Deploy storybook to Github Pages
        run: |
          cd client 
          npm install --legacy-peer-deps
          npm run deploy-storybook -- --ci
        env:
          GH_TOKEN: Dashboard:${{ secrets.GITHUB_TOKEN }}