name: Storybook
on:
  push:
    branches:
      - may-comp-lib
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        
      - name: Deploy storybook to Github Pages
        run: cd client npm install npm run deploy-storybook -- --ci
        env:
          GH_TOKEN: MyCompany:${{ secrets.GITHUB_TOKEN }}