name: turkeymarketing
on:
  push:
    branches: 
    paths:
    - 'marketing/**'
    - '.github/workflows/turkeymarketing.yml'
  workflow_dispatch:
  
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  turkeyGitops:
    uses: mozilla/hubs-ops/.github/workflows/turkeyGitops.yml@master
    with:
      registry: mozillareality
      codePath: marketing
      dockerfile: Dockerfile
    secrets:
      DOCKER_HUB_PWD: ${{ secrets.DOCKER_HUB_PWD }}
